#!/usr/bin/env bash
# Install the Free-Tier AI Orchestrator as a global `ofo` command so you can run
# it from any folder. Zero dependencies (uses the system python3). Idempotent.
#
#   ./install.sh              # install / update
#   ./install.sh --uninstall  # remove the launcher
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${OFO_BIN_DIR:-$HOME/.local/bin}"
LAUNCHER="$BIN_DIR/ofo"
CFG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/ofo"
GLOBAL_ENV="$CFG_DIR/.env"

if [ "${1:-}" = "--uninstall" ]; then
  rm -f "$LAUNCHER" && echo "removed $LAUNCHER" || true
  echo "Left your keys ($GLOBAL_ENV) and stats (~/.ofo) in place; delete them manually if you want."
  exit 0
fi

command -v python3 >/dev/null 2>&1 || { echo "error: python3 not found in PATH" >&2; exit 1; }

mkdir -p "$BIN_DIR" "$CFG_DIR"

# 1) launcher that works regardless of the current directory --------------------
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Free-Tier AI Orchestrator launcher (generated by install.sh). Runs from any dir;
# the agent operates on whatever folder you launch it in.
export PYTHONPATH="$PROJECT_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m orchestrator "\$@"
EOF
chmod +x "$LAUNCHER"
echo "✓ launcher installed: $LAUNCHER"

# 2) make provider keys available globally -------------------------------------
if [ ! -f "$GLOBAL_ENV" ]; then
  if [ -f "$PROJECT_DIR/.env" ]; then
    cp "$PROJECT_DIR/.env" "$GLOBAL_ENV"; chmod 600 "$GLOBAL_ENV"
    echo "✓ copied your keys to $GLOBAL_ENV (chmod 600) so 'ofo' finds them anywhere"
  else
    cp "$PROJECT_DIR/.env.example" "$GLOBAL_ENV" 2>/dev/null || true
    chmod 600 "$GLOBAL_ENV" 2>/dev/null || true
    echo "• created $GLOBAL_ENV — add at least one provider key to it"
  fi
else
  echo "• $GLOBAL_ENV already exists — left untouched"
fi

# 3) ensure the bin dir is on PATH ---------------------------------------------
case ":$PATH:" in
  *":$BIN_DIR:"*) echo "✓ $BIN_DIR is already on PATH" ;;
  *)
    for rc in "$HOME/.bashrc" "$HOME/.profile" "$HOME/.zshrc"; do
      [ -e "$rc" ] || continue
      if ! grep -q 'added by ofo install' "$rc" 2>/dev/null; then
        printf '\n# added by ofo install\nexport PATH="%s:$PATH"\n' "$BIN_DIR" >> "$rc"
        echo "✓ added $BIN_DIR to PATH in $rc"
      fi
    done
    echo "  → open a new shell, or run:  export PATH=\"$BIN_DIR:\$PATH\""
    ;;
esac

# 4) verify --------------------------------------------------------------------
if "$LAUNCHER" --version >/dev/null 2>&1; then
  echo "✓ verified: $("$LAUNCHER" --version)"
else
  echo "! verification failed — check that python3 works and the project path is intact" >&2
fi

cat <<EOF

Done — use it from any folder:
  ofo                         interactive agent in the current folder
  ofo "add tests for utils.py"
  ofo --list-models           show discovered free/free-tier models
  ofo --stats                 learned model leaderboard
Keys: $GLOBAL_ENV  (a project-local ./.env overrides it)
EOF
